# Analiza Algoritmilor - Proiect Etapa 2
# Algoritmii Rabin-Karp si Knuth-Morris-Pratt
# Grigore Lucian-Florin 324CDb
# Facultatea de Automatica si Calculatoare
# Universitatea Politehnica, Bucuresti

# Rularea unui test manual din cele predefinite:
# -> make build
# -> java Main test "in/test[TEST_NUMBER].in" "[FISIER OUTPUT]"
# -> cat [FISIER OUTPUT] pentru a vedea rezultatele
# -> make clean

# Rularea unui test manual cu argumente in linia de comanda:
# -> make build
# -> java Main manual "[PATTERN]" "[TEXT]" (recomand utilizarea ghilimelelor)
# rezultatele vor fi afisate la stdout
# -> make clean

build:
	javac -g Main.java

clean:
	find . -name "*.class" -type f -delete
