# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Nexys4DDR_Master.xdc

# Block Designs: bd/diszain/diszain.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diszain || ORIG_REF_NAME==diszain} -quiet] -quiet

# IP: bd/diszain/ip/diszain_util_vector_logic_0_0/diszain_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diszain_util_vector_logic_0_0 || ORIG_REF_NAME==diszain_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/diszain/ip/diszain_util_vector_logic_0_1/diszain_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diszain_util_vector_logic_0_1 || ORIG_REF_NAME==diszain_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/diszain/ip/diszain_xor_0_0/diszain_xor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diszain_xor_0_0 || ORIG_REF_NAME==diszain_xor_0_0} -quiet] -quiet

# IP: bd/diszain/ip/diszain_si_1_0/diszain_si_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diszain_si_1_0 || ORIG_REF_NAME==diszain_si_1_0} -quiet] -quiet

# IP: bd/diszain/ip/diszain_si_2_0/diszain_si_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diszain_si_2_0 || ORIG_REF_NAME==diszain_si_2_0} -quiet] -quiet

# XDC: bd/diszain/diszain_ooc.xdc
