webtalk_init -webtalk_dir /home/student1/Downloads/lab2/fratele_lui_gigia/fratele_lui_gigia.sim/sim_1/behav/xsim/xsim.dir/nununu_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar  4 11:50:53 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2729669" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9b4f3d0d-b06d-45d5-841e-c46eaf51fd20" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d20865facf064888aefddf6629f222ec" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "20" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "LinuxMint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 19.3 Tricia" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3700.874 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "450 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "125652_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3402451329 -regid "" -xml /home/student1/Downloads/lab2/fratele_lui_gigia/fratele_lui_gigia.sim/sim_1/behav/xsim/xsim.dir/nununu_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/student1/Downloads/lab2/fratele_lui_gigia/fratele_lui_gigia.sim/sim_1/behav/xsim/xsim.dir/nununu_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/student1/Downloads/lab2/fratele_lui_gigia/fratele_lui_gigia.sim/sim_1/behav/xsim/xsim.dir/nununu_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
