build:
	mpicc example.c -o example
	mpicc mpi_hello.c -o mpi_hello
	mpicc scatter_gather.c -o scatter_gather
	mpicc send_recv_array.c -o send_recv_array
clear:
	rm example mpi_hello scatter_gather send_recv_array
