# Protocoale de Comunicatii
# Tema 2
# Aplicatie Client-Server
# Grigore Lucian-Florin 324CD

build: 
	gcc -Wall server.c -o server -lm
	gcc -Wall subscriber.c -o subscriber

clean: 
	rm -f server subscriber