build: holograme.cpp scurt.cpp umbre.cpp
	g++ holograme.cpp -o holograme
	g++ scurt.cpp -o scurt 
	g++ umbre.cpp -o umbre

run-p1: 
	./holograme

run-p2:
	./scurt

run-p3:
	./umbre

clean:
	rm -f holograme scurt umbre