# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Nexys4DDR_Master.xdc

# Block Designs: bd/prima_zi_de_scoala/prima_zi_de_scoala.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prima_zi_de_scoala || ORIG_REF_NAME==prima_zi_de_scoala} -quiet] -quiet

# IP: bd/prima_zi_de_scoala/ip/prima_zi_de_scoala_util_vector_logic_0_0/prima_zi_de_scoala_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prima_zi_de_scoala_util_vector_logic_0_0 || ORIG_REF_NAME==prima_zi_de_scoala_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/prima_zi_de_scoala/ip/prima_zi_de_scoala_util_vector_logic_1_0/prima_zi_de_scoala_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prima_zi_de_scoala_util_vector_logic_1_0 || ORIG_REF_NAME==prima_zi_de_scoala_util_vector_logic_1_0} -quiet] -quiet

# XDC: bd/prima_zi_de_scoala/prima_zi_de_scoala_ooc.xdc
