#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Feb 26 10:38:00 EET 2020
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 0eb35121006f4776b1e303a63c11f461 --incr --debug typical --relax --mt 8 -L util_vector_logic_v2_0_1 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot prima_zi_de_scoala_wrapper_behav xil_defaultlib.prima_zi_de_scoala_wrapper xil_defaultlib.glbl -log elaborate.log"
xelab -wto 0eb35121006f4776b1e303a63c11f461 --incr --debug typical --relax --mt 8 -L util_vector_logic_v2_0_1 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot prima_zi_de_scoala_wrapper_behav xil_defaultlib.prima_zi_de_scoala_wrapper xil_defaultlib.glbl -log elaborate.log

