build:
	mpicc -o hello_world hello_world.c
	mpicc -o communication communication.c
	mpicc -o sendrecv sendrecv.c
	mpicc -o non_blocking non_blocking.c
	mpicc -o custom_type custom_type.c
	mpicc -o collective collective.c

clean:
	rm -rf hello_world communication sendrecv non_blocking custom_type collective
