# Proiectarea Algoritmilor - Tema1
# Grigore Lucian-Florin 324CD

build:
	gcc -Wall teme.c -o teme
	gcc -Wall magic.c -o magic -lm
	gcc -Wall ratisoare.c -o ratisoare
	gcc -Wall joc.c -o joc

run-p1: 
	./teme

run-p2:
	./magic

run-p3: 
	./ratisoare

run-p4: 
	./joc

clean:
	rm -f teme joc magic ratisoare
