# Darius-Florentin Neatu <neatudarius@gmail.com>
# Copyright 2018

# ignorati
# Makegfile intern folosit de checker

all: build_verif

build_verif:
	g++ -std=c++11 -Wall -Wextra -lm -O3 ${ONLINE_JUDGE} _utils/verif.cpp -o verif

clean:
	rm -f verif
