# Proiectarea Algoritmilor - Tema1
# Grigore Lucian-Florin 324CD

all: build

build:
	gcc teme.c -o teme 
	gcc magic.c -o magic 
	gcc ratisoare.c -o ratisoare 
	gcc joc.c -o joc

run-p1: teme
	./teme

run-p2: magic
	./magic

run-p3: ratisoare
	./ratisoare

run-p4: joc
	./joc

clean:
	rm -f teme joc magic ratisoare